---
language: python
python: "2.7"

sudo: required
dist: trusty

install:
  - sudo apt-get install -y software-properties-common python-software-properties
  - sudo add-apt-repository -y ppa:ansible/ansible
  - sudo apt-get update -y
  - sudo apt-get install -y ansible
  - echo 'oslab-test' | sudo tee -a /etc/ansible/hosts
  - ansible --version
  - 'printf "[defaults]\nroles_path=../" > ansible.cfg'

env:
  - ANSIBLE_HOST_KEY_CHECKING=False

script:
  - ansible-playbook tests/test.yml -v

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
